### PR TITLE
Use inputted DB connection for sqlstore

### PR DESCRIPTION
**Pull request by ajoseps**
This change is meant to go with omni3x/taker-api-server#234

### CODE REVIEW

**Comment by jtai-omniex** [comment]
why does this help?

**Comment by ajoseps** [comment]
> why does this help?

i don't know but it does seem to

**Comment by jtai-omniex** [comment]
> > why does this help?
> 
> i don't know but it does seem to. Additionally, it's generally recommended to use one global DB connection per application

you're talking about a connection pool right? not just a single global db connection

**Comment by ajoseps** [comment]
> > > why does this help?
> > 
> > 
> > i don't know but it does seem to. Additionally, it's generally recommended to use one global DB connection per application
> 
> you're talking about a connection pool right? not just a single global db connection

yes, currently there are two connection pools for the same DB

**Pull request merged**
